version: '3.7'
services:
  my-db:
    image: postgres:16.1-alpine
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: travel_agency
    restart: unless-stopped
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-agency
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-db:5432/travel_agency
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8080:8080
    restart: on-failure
    links:
      - my-db
volumes:
  postgres-data: